language: perl
perl:
  - "5.14"

before_install:
  - sudo apt-get update
  - sudo apt-get install muscle
  - sudo apt-get install ncbi-blast+
  - sudo apt-get install mummer

install:
  - cpanm --verbose --installdeps --notest .
